/*
 * ONI Seed Browser
 * Copyright (C) 2024 Stefan Oltmann
 * https://stefan-oltmann.de/oni-seed-browser
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package service

/**
 * 25 entries
 */
val jsonSampleSearchResponse: String = """
      [
      {
        "coordinate": "M-BAD-C-638010066-0-0-0",
        "cluster": "M-BAD-C",
        "dlcs": [
          "FrostyPlanet",
          "SpacedOut"
        ],
        "worldTraitsOfStarter": [
          "MagmaVents",
          "DistressSignal"
        ],
        "geysersCountOfStarter": {
          "OIL_WELL": 4,
          "COOL_STEAM": 1,
          "NATURAL_GAS": 1,
          "HOT_CO2": 1,
          "LEAKY_OIL_FISSURE": 1,
          "MINOR_VOLCANO": 1
        },
        "starMapEntryCounts": {
          "MiniBadlandsStart": 1,
          "MiniRadioactiveOceanWarp": 1,
          "MiniMetallicSwampy": 1,
          "MiniForestFrozen": 1,
          "MiniFlipped": 1,
          "TundraMoonlet": 1,
          "MarshyMoonlet": 1,
          "MooMoonlet": 1,
          "WaterMoonlet": 1,
          "NiobiumMoonlet": 1,
          "RegolithMoonlet": 1,
          "TemporalTear": 1,
          "HarvestableSpacePOI_SwampyOreField": 1,
          "HarvestableSpacePOI_OrganicMassField": 2,
          "HarvestableSpacePOI_FrozenOreField": 1,
          "HarvestableSpacePOI_GlimmeringAsteroidField": 1,
          "HarvestableSpacePOI_HeliumCloud": 1,
          "HarvestableSpacePOI_GildedAsteroidField": 1,
          "HarvestableSpacePOI_OilyAsteroidField": 3,
          "HarvestableSpacePOI_RadioactiveGasCloud": 4,
          "HarvestableSpacePOI_RadioactiveAsteroidField": 1,
          "HarvestableSpacePOI_InterstellarOcean": 4,
          "HarvestableSpacePOI_ChlorineCloud": 2,
          "HarvestableSpacePOI_SatelliteField": 1,
          "HarvestableSpacePOI_CarbonAsteroidField": 1,
          "HarvestableSpacePOI_GasGiantCloud": 1,
          "ArtifactSpacePOI_RussellsTeapot": 1,
          "ArtifactSpacePOI_GravitasSpaceStation8": 1,
          "ArtifactSpacePOI_GravitasSpaceStation3": 1,
          "ArtifactSpacePOI_GravitasSpaceStation7": 1,
          "ArtifactSpacePOI_GravitasSpaceStation2": 1
        }
      },
      {
        "coordinate": "M-BAD-C-1900407801-0-0-0",
        "cluster": "M-BAD-C",
        "dlcs": [
          "FrostyPlanet",
          "SpacedOut"
        ],
        "worldTraitsOfStarter": [
          "SlimeSplats"
        ],
        "geysersCountOfStarter": {
          "OIL_WELL": 5,
          "COOL_STEAM": 1,
          "CHLORINE": 1,
          "MINOR_VOLCANO": 1,
          "HOT_CO2": 1,
          "HOT_POLLUTED_O2": 1
        },
        "starMapEntryCounts": {
          "MiniBadlandsStart": 1,
          "MiniRadioactiveOceanWarp": 1,
          "MiniMetallicSwampy": 1,
          "MiniForestFrozen": 1,
          "MiniFlipped": 1,
          "TundraMoonlet": 1,
          "MarshyMoonlet": 1,
          "MooMoonlet": 1,
          "WaterMoonlet": 1,
          "NiobiumMoonlet": 1,
          "RegolithMoonlet": 1,
          "TemporalTear": 1,
          "HarvestableSpacePOI_SwampyOreField": 1,
          "HarvestableSpacePOI_OrganicMassField": 1,
          "HarvestableSpacePOI_GildedAsteroidField": 3,
          "HarvestableSpacePOI_GlimmeringAsteroidField": 2,
          "HarvestableSpacePOI_FrozenOreField": 1,
          "HarvestableSpacePOI_HeliumCloud": 1,
          "HarvestableSpacePOI_OilyAsteroidField": 3,
          "HarvestableSpacePOI_RadioactiveGasCloud": 1,
          "HarvestableSpacePOI_RadioactiveAsteroidField": 1,
          "HarvestableSpacePOI_RockyAsteroidField": 2,
          "HarvestableSpacePOI_InterstellarIceField": 1,
          "HarvestableSpacePOI_InterstellarOcean": 1,
          "HarvestableSpacePOI_ForestyOreField": 1,
          "HarvestableSpacePOI_OxidizedAsteroidField": 1,
          "HarvestableSpacePOI_OxygenRichAsteroidField": 1,
          "HarvestableSpacePOI_IceAsteroidField": 2,
          "HarvestableSpacePOI_MetallicAsteroidField": 1,
          "ArtifactSpacePOI_GravitasSpaceStation6": 1,
          "ArtifactSpacePOI_RussellsTeapot": 1,
          "ArtifactSpacePOI_GravitasSpaceStation5": 1,
          "ArtifactSpacePOI_GravitasSpaceStation8": 1,
          "ArtifactSpacePOI_GravitasSpaceStation2": 1,
          "ArtifactSpacePOI_GravitasSpaceStation7": 1
        }
      },
      {
        "coordinate": "M-BAD-C-1046768072-0-0-0",
        "cluster": "M-BAD-C",
        "dlcs": [
          "FrostyPlanet",
          "SpacedOut"
        ],
        "worldTraitsOfStarter": [
          "MetalPoor",
          "RadioactiveCrust"
        ],
        "geysersCountOfStarter": {
          "OIL_WELL": 5,
          "COOL_STEAM": 1,
          "NATURAL_GAS": 1,
          "HOT_CO2": 1,
          "HYDROGEN": 1,
          "INFECTIOUS_POLLUTED_O2": 1
        },
        "starMapEntryCounts": {
          "MiniBadlandsStart": 1,
          "MiniRadioactiveOceanWarp": 1,
          "MiniMetallicSwampy": 1,
          "MiniForestFrozen": 1,
          "MiniFlipped": 1,
          "TundraMoonlet": 1,
          "MarshyMoonlet": 1,
          "MooMoonlet": 1,
          "WaterMoonlet": 1,
          "NiobiumMoonlet": 1,
          "RegolithMoonlet": 1,
          "TemporalTear": 1,
          "HarvestableSpacePOI_SwampyOreField": 1,
          "HarvestableSpacePOI_OrganicMassField": 3,
          "HarvestableSpacePOI_FrozenOreField": 2,
          "HarvestableSpacePOI_GlimmeringAsteroidField": 1,
          "HarvestableSpacePOI_OilyAsteroidField": 2,
          "HarvestableSpacePOI_HeliumCloud": 1,
          "HarvestableSpacePOI_GildedAsteroidField": 1,
          "HarvestableSpacePOI_RadioactiveGasCloud": 2,
          "HarvestableSpacePOI_RadioactiveAsteroidField": 3,
          "HarvestableSpacePOI_RockyAsteroidField": 1,
          "HarvestableSpacePOI_ForestyOreField": 2,
          "HarvestableSpacePOI_CarbonAsteroidField": 1,
          "HarvestableSpacePOI_ChlorineCloud": 1,
          "HarvestableSpacePOI_OxidizedAsteroidField": 1,
          "HarvestableSpacePOI_SaltyAsteroidField": 1,
          "HarvestableSpacePOI_IceAsteroidField": 1,
          "ArtifactSpacePOI_GravitasSpaceStation6": 1,
          "ArtifactSpacePOI_RussellsTeapot": 1,
          "ArtifactSpacePOI_GravitasSpaceStation5": 1,
          "ArtifactSpacePOI_GravitasSpaceStation8": 1,
          "ArtifactSpacePOI_GravitasSpaceStation2": 1,
          "ArtifactSpacePOI_GravitasSpaceStation3": 1
        }
      },
      {
        "coordinate": "M-BAD-C-187201784-0-0-0",
        "cluster": "M-BAD-C",
        "dlcs": [
          "FrostyPlanet",
          "SpacedOut"
        ],
        "worldTraitsOfStarter": [
          "MetalRich",
          "SlimeSplats"
        ],
        "geysersCountOfStarter": {
          "OIL_WELL": 5,
          "COOL_STEAM": 1,
          "CHLORINE": 2,
          "LEAKY_OIL_FISSURE": 1,
          "HOT_CO2": 1
        },
        "starMapEntryCounts": {
          "MiniBadlandsStart": 1,
          "MiniRadioactiveOceanWarp": 1,
          "MiniMetallicSwampy": 1,
          "MiniForestFrozen": 1,
          "MiniFlipped": 1,
          "TundraMoonlet": 1,
          "MarshyMoonlet": 1,
          "MooMoonlet": 1,
          "WaterMoonlet": 1,
          "NiobiumMoonlet": 1,
          "RegolithMoonlet": 1,
          "TemporalTear": 1,
          "HarvestableSpacePOI_SwampyOreField": 1,
          "HarvestableSpacePOI_OrganicMassField": 1,
          "HarvestableSpacePOI_HeliumCloud": 1,
          "HarvestableSpacePOI_OilyAsteroidField": 1,
          "HarvestableSpacePOI_GildedAsteroidField": 2,
          "HarvestableSpacePOI_GlimmeringAsteroidField": 1,
          "HarvestableSpacePOI_FrozenOreField": 2,
          "HarvestableSpacePOI_RadioactiveAsteroidField": 3,
          "HarvestableSpacePOI_RadioactiveGasCloud": 2,
          "HarvestableSpacePOI_RockyAsteroidField": 2,
          "HarvestableSpacePOI_InterstellarIceField": 1,
          "HarvestableSpacePOI_ForestyOreField": 1,
          "HarvestableSpacePOI_CarbonAsteroidField": 1,
          "HarvestableSpacePOI_SaltyAsteroidField": 1,
          "HarvestableSpacePOI_MetallicAsteroidField": 1,
          "HarvestableSpacePOI_ChlorineCloud": 1,
          "HarvestableSpacePOI_OxidizedAsteroidField": 1,
          "ArtifactSpacePOI_GravitasSpaceStation6": 1,
          "ArtifactSpacePOI_RussellsTeapot": 1,
          "ArtifactSpacePOI_GravitasSpaceStation2": 1,
          "ArtifactSpacePOI_GravitasSpaceStation3": 1
        }
      },
      {
        "coordinate": "M-BAD-C-1518279474-0-0-0",
        "cluster": "M-BAD-C",
        "dlcs": [
          "FrostyPlanet",
          "SpacedOut"
        ],
        "worldTraitsOfStarter": [
          "DeepOil",
          "Geodes"
        ],
        "geysersCountOfStarter": {
          "OIL_WELL": 14,
          "COOL_STEAM": 1,
          "CHLORINE": 1,
          "HOT_CO2": 1,
          "NATURAL_GAS": 1,
          "INFECTIOUS_POLLUTED_O2": 1
        },
        "starMapEntryCounts": {
          "MiniBadlandsStart": 1,
          "MiniRadioactiveOceanWarp": 1,
          "MiniMetallicSwampy": 1,
          "MiniForestFrozen": 1,
          "MiniFlipped": 1,
          "TundraMoonlet": 1,
          "MarshyMoonlet": 1,
          "MooMoonlet": 1,
          "WaterMoonlet": 1,
          "NiobiumMoonlet": 1,
          "RegolithMoonlet": 1,
          "TemporalTear": 1,
          "HarvestableSpacePOI_SwampyOreField": 1,
          "HarvestableSpacePOI_OrganicMassField": 4,
          "HarvestableSpacePOI_GlimmeringAsteroidField": 1,
          "HarvestableSpacePOI_HeliumCloud": 1,
          "HarvestableSpacePOI_FrozenOreField": 1,
          "HarvestableSpacePOI_OilyAsteroidField": 2,
          "HarvestableSpacePOI_GildedAsteroidField": 2,
          "HarvestableSpacePOI_RadioactiveGasCloud": 1,
          "HarvestableSpacePOI_RadioactiveAsteroidField": 1,
          "HarvestableSpacePOI_SandyOreField": 1,
          "HarvestableSpacePOI_InterstellarOcean": 1,
          "HarvestableSpacePOI_SatelliteField": 2,
          "HarvestableSpacePOI_IceAsteroidField": 3,
          "HarvestableSpacePOI_GasGiantCloud": 1,
          "HarvestableSpacePOI_MetallicAsteroidField": 1,
          "HarvestableSpacePOI_OxidizedAsteroidField": 1,
          "ArtifactSpacePOI_GravitasSpaceStation4": 1,
          "ArtifactSpacePOI_RussellsTeapot": 1,
          "ArtifactSpacePOI_GravitasSpaceStation5": 1,
          "ArtifactSpacePOI_GravitasSpaceStation8": 1,
          "ArtifactSpacePOI_GravitasSpaceStation7": 1,
          "ArtifactSpacePOI_GravitasSpaceStation2": 1
        }
      },
        {
          "coordinate": "SNDST-C-971302415-0-0-0",
          "cluster": "SNDST-C",
          "dlcs": [
            "FrostyPlanet",
            "SpacedOut"
          ],
          "worldTraitsOfStarter": [],
          "geysersCountOfStarter": {
            "COOL_STEAM": 2,
            "COOL_SLUSH_WATER": 1,
            "COOL_SALT_WATER": 1,
            "NATURAL_GAS": 2,
            "MINOR_VOLCANO": 3,
            "POLLUTED_WATER": 1
          },
          "starMapEntryCounts": {
            "TerraMoonlet": 1,
            "IdealLandingSite": 1,
            "WarpOilySwamp": 1,
            "TundraMoonlet": 1,
            "MarshyMoonlet": 1,
            "MooMoonlet": 1,
            "WaterMoonlet": 1,
            "NiobiumMoonlet": 1,
            "RegolithMoonlet": 1,
            "TemporalTear": 1,
            "HarvestableSpacePOI_SandyOreField": 1,
            "HarvestableSpacePOI_OrganicMassField": 2,
            "HarvestableSpacePOI_HeliumCloud": 2,
            "HarvestableSpacePOI_GlimmeringAsteroidField": 1,
            "HarvestableSpacePOI_OilyAsteroidField": 3,
            "HarvestableSpacePOI_GildedAsteroidField": 1,
            "HarvestableSpacePOI_FrozenOreField": 2,
            "HarvestableSpacePOI_RadioactiveAsteroidField": 2,
            "HarvestableSpacePOI_RadioactiveGasCloud": 2,
            "HarvestableSpacePOI_RockyAsteroidField": 2,
            "HarvestableSpacePOI_InterstellarIceField": 1,
            "HarvestableSpacePOI_SwampyOreField": 1,
            "HarvestableSpacePOI_OxidizedAsteroidField": 1,
            "HarvestableSpacePOI_GasGiantCloud": 1,
            "HarvestableSpacePOI_IceAsteroidField": 1,
            "HarvestableSpacePOI_MetallicAsteroidField": 1,
            "ArtifactSpacePOI_GravitasSpaceStation4": 1,
            "ArtifactSpacePOI_RussellsTeapot": 1,
            "ArtifactSpacePOI_GravitasSpaceStation5": 1,
            "ArtifactSpacePOI_GravitasSpaceStation3": 1,
            "ArtifactSpacePOI_GravitasSpaceStation8": 1,
            "ArtifactSpacePOI_GravitasSpaceStation7": 1
          }
        },
        {
          "coordinate": "SNDST-C-1286516645-0-0-0",
          "cluster": "SNDST-C",
          "dlcs": [
            "FrostyPlanet",
            "SpacedOut"
          ],
          "worldTraitsOfStarter": [],
          "geysersCountOfStarter": {
            "COOL_STEAM": 1,
            "COOL_SALT_WATER": 1,
            "COOL_SLUSH_WATER": 1,
            "NATURAL_GAS": 1,
            "MINOR_VOLCANO": 3,
            "VOLCANO": 2,
            "HYDROGEN": 1
          },
          "starMapEntryCounts": {
            "TerraMoonlet": 1,
            "IdealLandingSite": 1,
            "WarpOilySwamp": 1,
            "TundraMoonlet": 1,
            "MarshyMoonlet": 1,
            "MooMoonlet": 1,
            "WaterMoonlet": 1,
            "NiobiumMoonlet": 1,
            "RegolithMoonlet": 1,
            "TemporalTear": 1,
            "HarvestableSpacePOI_SandyOreField": 1,
            "HarvestableSpacePOI_OrganicMassField": 3,
            "HarvestableSpacePOI_FrozenOreField": 2,
            "HarvestableSpacePOI_HeliumCloud": 2,
            "HarvestableSpacePOI_GlimmeringAsteroidField": 1,
            "HarvestableSpacePOI_OilyAsteroidField": 2,
            "HarvestableSpacePOI_GildedAsteroidField": 1,
            "HarvestableSpacePOI_RadioactiveAsteroidField": 1,
            "HarvestableSpacePOI_RadioactiveGasCloud": 1,
            "HarvestableSpacePOI_InterstellarIceField": 1,
            "HarvestableSpacePOI_InterstellarOcean": 1,
            "HarvestableSpacePOI_SwampyOreField": 1,
            "HarvestableSpacePOI_OxidizedAsteroidField": 2,
            "HarvestableSpacePOI_MetallicAsteroidField": 3,
            "HarvestableSpacePOI_GasGiantCloud": 1,
            "HarvestableSpacePOI_IceAsteroidField": 1,
            "ArtifactSpacePOI_GravitasSpaceStation4": 1,
            "ArtifactSpacePOI_RussellsTeapot": 1,
            "ArtifactSpacePOI_GravitasSpaceStation2": 1
          }
        },
        {
          "coordinate": "SNDST-C-1282979688-0-0-0",
          "cluster": "SNDST-C",
          "dlcs": [
            "FrostyPlanet",
            "SpacedOut"
          ],
          "worldTraitsOfStarter": [],
          "geysersCountOfStarter": {
            "COOL_STEAM": 1,
            "COOL_SLUSH_WATER": 1,
            "COOL_SALT_WATER": 1,
            "NATURAL_GAS": 2,
            "MINOR_VOLCANO": 2,
            "CHLORINE": 2
          },
          "starMapEntryCounts": {
            "TerraMoonlet": 2,
            "IdealLandingSite": 2,
            "WarpOilySwamp": 2,
            "TundraMoonlet": 2,
            "MarshyMoonlet": 2,
            "MooMoonlet": 2,
            "WaterMoonlet": 2,
            "NiobiumMoonlet": 2,
            "RegolithMoonlet": 2,
            "TemporalTear": 2,
            "HarvestableSpacePOI_SandyOreField": 2,
            "HarvestableSpacePOI_OrganicMassField": 6,
            "HarvestableSpacePOI_FrozenOreField": 6,
            "HarvestableSpacePOI_HeliumCloud": 3,
            "HarvestableSpacePOI_GlimmeringAsteroidField": 2,
            "HarvestableSpacePOI_OilyAsteroidField": 3,
            "HarvestableSpacePOI_GildedAsteroidField": 2,
            "HarvestableSpacePOI_RadioactiveAsteroidField": 2,
            "HarvestableSpacePOI_RadioactiveGasCloud": 2,
            "HarvestableSpacePOI_InterstellarIceField": 2,
            "HarvestableSpacePOI_InterstellarOcean": 3,
            "HarvestableSpacePOI_SwampyOreField": 1,
            "HarvestableSpacePOI_OxidizedAsteroidField": 2,
            "HarvestableSpacePOI_MetallicAsteroidField": 4,
            "HarvestableSpacePOI_GasGiantCloud": 4,
            "HarvestableSpacePOI_IceAsteroidField": 1,
            "ArtifactSpacePOI_GravitasSpaceStation4": 1,
            "ArtifactSpacePOI_RussellsTeapot": 2,
            "ArtifactSpacePOI_GravitasSpaceStation2": 1,
            "HarvestableSpacePOI_SatelliteField": 1,
            "HarvestableSpacePOI_ChlorineCloud": 2,
            "ArtifactSpacePOI_GravitasSpaceStation6": 1
          }
        },
        {
          "coordinate": "SNDST-C-1128328159-0-0-0",
          "cluster": "SNDST-C",
          "dlcs": [
            "FrostyPlanet",
            "SpacedOut"
          ],
          "worldTraitsOfStarter": [],
          "geysersCountOfStarter": {
            "COOL_STEAM": 1,
            "COOL_SLUSH_WATER": 1,
            "COOL_SALT_WATER": 1,
            "NATURAL_GAS": 1,
            "MINOR_VOLCANO": 3,
            "HOT_POLLUTED_O2": 1,
            "HYDROGEN": 1,
            "POLLUTED_WATER": 1
          },
          "starMapEntryCounts": {
            "TerraMoonlet": 1,
            "IdealLandingSite": 1,
            "WarpOilySwamp": 1,
            "TundraMoonlet": 1,
            "MarshyMoonlet": 1,
            "MooMoonlet": 1,
            "WaterMoonlet": 1,
            "NiobiumMoonlet": 1,
            "RegolithMoonlet": 1,
            "TemporalTear": 1,
            "HarvestableSpacePOI_SandyOreField": 1,
            "HarvestableSpacePOI_OrganicMassField": 3,
            "HarvestableSpacePOI_HeliumCloud": 1,
            "HarvestableSpacePOI_FrozenOreField": 1,
            "HarvestableSpacePOI_OilyAsteroidField": 1,
            "HarvestableSpacePOI_GildedAsteroidField": 2,
            "HarvestableSpacePOI_GlimmeringAsteroidField": 1,
            "HarvestableSpacePOI_RadioactiveGasCloud": 1,
            "HarvestableSpacePOI_RadioactiveAsteroidField": 2,
            "HarvestableSpacePOI_SwampyOreField": 1,
            "HarvestableSpacePOI_InterstellarIceField": 1,
            "HarvestableSpacePOI_RockyAsteroidField": 1,
            "HarvestableSpacePOI_IceAsteroidField": 1,
            "HarvestableSpacePOI_SatelliteField": 1,
            "HarvestableSpacePOI_GasGiantCloud": 2,
            "HarvestableSpacePOI_SaltyAsteroidField": 2,
            "HarvestableSpacePOI_OxygenRichAsteroidField": 1,
            "HarvestableSpacePOI_OxidizedAsteroidField": 1,
            "ArtifactSpacePOI_GravitasSpaceStation1": 1,
            "ArtifactSpacePOI_RussellsTeapot": 1,
            "ArtifactSpacePOI_GravitasSpaceStation5": 1,
            "ArtifactSpacePOI_GravitasSpaceStation8": 1,
            "ArtifactSpacePOI_GravitasSpaceStation2": 1
          }
        },
        {
          "coordinate": "SNDST-C-327283460-0-0-0",
          "cluster": "SNDST-C",
          "dlcs": [
            "FrostyPlanet",
            "SpacedOut"
          ],
          "worldTraitsOfStarter": [],
          "geysersCountOfStarter": {
            "COOL_STEAM": 1,
            "COOL_SLUSH_WATER": 1,
            "COOL_SALT_WATER": 1,
            "NATURAL_GAS": 1,
            "MINOR_VOLCANO": 3,
            "HOT_POLLUTED_O2": 1,
            "POLLUTED_WATER": 1,
            "LIQUID_CO2": 1
          },
          "starMapEntryCounts": {
            "TerraMoonlet": 2,
            "IdealLandingSite": 2,
            "WarpOilySwamp": 2,
            "TundraMoonlet": 2,
            "MarshyMoonlet": 2,
            "MooMoonlet": 2,
            "WaterMoonlet": 2,
            "NiobiumMoonlet": 2,
            "RegolithMoonlet": 2,
            "TemporalTear": 2,
            "HarvestableSpacePOI_SandyOreField": 2,
            "HarvestableSpacePOI_OrganicMassField": 5,
            "HarvestableSpacePOI_HeliumCloud": 2,
            "HarvestableSpacePOI_FrozenOreField": 2,
            "HarvestableSpacePOI_OilyAsteroidField": 3,
            "HarvestableSpacePOI_GildedAsteroidField": 3,
            "HarvestableSpacePOI_GlimmeringAsteroidField": 4,
            "HarvestableSpacePOI_RadioactiveGasCloud": 2,
            "HarvestableSpacePOI_RadioactiveAsteroidField": 4,
            "HarvestableSpacePOI_SwampyOreField": 2,
            "HarvestableSpacePOI_InterstellarIceField": 1,
            "HarvestableSpacePOI_RockyAsteroidField": 2,
            "HarvestableSpacePOI_IceAsteroidField": 1,
            "HarvestableSpacePOI_SatelliteField": 2,
            "HarvestableSpacePOI_GasGiantCloud": 4,
            "HarvestableSpacePOI_SaltyAsteroidField": 2,
            "HarvestableSpacePOI_OxygenRichAsteroidField": 2,
            "HarvestableSpacePOI_OxidizedAsteroidField": 1,
            "ArtifactSpacePOI_GravitasSpaceStation1": 1,
            "ArtifactSpacePOI_RussellsTeapot": 2,
            "ArtifactSpacePOI_GravitasSpaceStation5": 1,
            "ArtifactSpacePOI_GravitasSpaceStation8": 2,
            "ArtifactSpacePOI_GravitasSpaceStation2": 2,
            "HarvestableSpacePOI_ForestyOreField": 2,
            "HarvestableSpacePOI_CarbonAsteroidField": 1,
            "HarvestableSpacePOI_ChlorineCloud": 1,
            "ArtifactSpacePOI_GravitasSpaceStation4": 1
          }
        },
        {
          "coordinate": "SNDST-C-1680343943-0-0-0",
          "cluster": "SNDST-C",
          "dlcs": [
            "FrostyPlanet",
            "SpacedOut"
          ],
          "worldTraitsOfStarter": [],
          "geysersCountOfStarter": {
            "COOL_STEAM": 2,
            "COOL_SALT_WATER": 1,
            "COOL_SLUSH_WATER": 1,
            "NATURAL_GAS": 2,
            "MINOR_VOLCANO": 3,
            "VOLCANO": 1
          },
          "starMapEntryCounts": {
            "TerraMoonlet": 1,
            "IdealLandingSite": 1,
            "WarpOilySwamp": 1,
            "TundraMoonlet": 1,
            "MarshyMoonlet": 1,
            "MooMoonlet": 1,
            "WaterMoonlet": 1,
            "NiobiumMoonlet": 1,
            "RegolithMoonlet": 1,
            "TemporalTear": 1,
            "HarvestableSpacePOI_SandyOreField": 1,
            "HarvestableSpacePOI_OrganicMassField": 2,
            "HarvestableSpacePOI_FrozenOreField": 1,
            "HarvestableSpacePOI_GlimmeringAsteroidField": 2,
            "HarvestableSpacePOI_GildedAsteroidField": 1,
            "HarvestableSpacePOI_HeliumCloud": 1,
            "HarvestableSpacePOI_OilyAsteroidField": 1,
            "HarvestableSpacePOI_RadioactiveAsteroidField": 3,
            "HarvestableSpacePOI_RadioactiveGasCloud": 1,
            "HarvestableSpacePOI_InterstellarOcean": 3,
            "HarvestableSpacePOI_RockyAsteroidField": 1,
            "HarvestableSpacePOI_SatelliteField": 1,
            "HarvestableSpacePOI_CarbonAsteroidField": 3,
            "HarvestableSpacePOI_IceAsteroidField": 1,
            "HarvestableSpacePOI_OxidizedAsteroidField": 1,
            "HarvestableSpacePOI_OxygenRichAsteroidField": 1,
            "ArtifactSpacePOI_RussellsTeapot": 1
          }
        },
        {
          "coordinate": "SNDST-C-1665511411-0-0-0",
          "cluster": "SNDST-C",
          "dlcs": [
            "FrostyPlanet",
            "SpacedOut"
          ],
          "worldTraitsOfStarter": [],
          "geysersCountOfStarter": {
            "COOL_STEAM": 1,
            "COOL_SALT_WATER": 1,
            "COOL_SLUSH_WATER": 1,
            "NATURAL_GAS": 1,
            "MINOR_VOLCANO": 3,
            "HOT_POLLUTED_O2": 2,
            "CHLORINE": 1
          },
          "starMapEntryCounts": {
            "TerraMoonlet": 1,
            "IdealLandingSite": 1,
            "WarpOilySwamp": 1,
            "TundraMoonlet": 1,
            "MarshyMoonlet": 1,
            "MooMoonlet": 1,
            "WaterMoonlet": 1,
            "NiobiumMoonlet": 1,
            "RegolithMoonlet": 1,
            "TemporalTear": 1,
            "HarvestableSpacePOI_SandyOreField": 1,
            "HarvestableSpacePOI_OrganicMassField": 2,
            "HarvestableSpacePOI_HeliumCloud": 1,
            "HarvestableSpacePOI_GlimmeringAsteroidField": 2,
            "HarvestableSpacePOI_FrozenOreField": 2,
            "HarvestableSpacePOI_GildedAsteroidField": 1,
            "HarvestableSpacePOI_OilyAsteroidField": 3,
            "HarvestableSpacePOI_RadioactiveAsteroidField": 2,
            "HarvestableSpacePOI_RadioactiveGasCloud": 1,
            "HarvestableSpacePOI_InterstellarOcean": 1,
            "HarvestableSpacePOI_RockyAsteroidField": 1,
            "HarvestableSpacePOI_InterstellarIceField": 2,
            "HarvestableSpacePOI_ChlorineCloud": 1,
            "HarvestableSpacePOI_OxidizedAsteroidField": 1,
            "HarvestableSpacePOI_GasGiantCloud": 1,
            "HarvestableSpacePOI_SaltyAsteroidField": 1,
            "ArtifactSpacePOI_GravitasSpaceStation1": 1,
            "ArtifactSpacePOI_GravitasSpaceStation7": 1
          }
        },
        {
          "coordinate": "SNDST-C-1566236017-0-0-0",
          "cluster": "SNDST-C",
          "dlcs": [
            "FrostyPlanet",
            "SpacedOut"
          ],
          "worldTraitsOfStarter": [],
          "geysersCountOfStarter": {
            "COOL_STEAM": 1,
            "COOL_SLUSH_WATER": 1,
            "COOL_SALT_WATER": 1,
            "NATURAL_GAS": 1,
            "MINOR_VOLCANO": 3,
            "VOLCANO": 1,
            "HOT_POLLUTED_O2": 1,
            "LIQUID_CO2": 1
          },
          "starMapEntryCounts": {
            "TerraMoonlet": 1,
            "IdealLandingSite": 1,
            "WarpOilySwamp": 1,
            "TundraMoonlet": 1,
            "MarshyMoonlet": 1,
            "MooMoonlet": 1,
            "WaterMoonlet": 1,
            "NiobiumMoonlet": 1,
            "RegolithMoonlet": 1,
            "TemporalTear": 1,
            "HarvestableSpacePOI_SandyOreField": 1,
            "HarvestableSpacePOI_OrganicMassField": 2,
            "HarvestableSpacePOI_GlimmeringAsteroidField": 3,
            "HarvestableSpacePOI_OilyAsteroidField": 1,
            "HarvestableSpacePOI_HeliumCloud": 1,
            "HarvestableSpacePOI_FrozenOreField": 2,
            "HarvestableSpacePOI_GildedAsteroidField": 1,
            "HarvestableSpacePOI_RadioactiveGasCloud": 1,
            "HarvestableSpacePOI_RadioactiveAsteroidField": 1,
            "HarvestableSpacePOI_ForestyOreField": 1,
            "HarvestableSpacePOI_InterstellarOcean": 1,
            "HarvestableSpacePOI_InterstellarIceField": 1,
            "HarvestableSpacePOI_MetallicAsteroidField": 1,
            "HarvestableSpacePOI_GasGiantCloud": 1,
            "HarvestableSpacePOI_IceAsteroidField": 1,
            "HarvestableSpacePOI_OxidizedAsteroidField": 2,
            "HarvestableSpacePOI_SatelliteField": 2,
            "ArtifactSpacePOI_RussellsTeapot": 1,
            "ArtifactSpacePOI_GravitasSpaceStation3": 1,
            "ArtifactSpacePOI_GravitasSpaceStation7": 1,
            "ArtifactSpacePOI_GravitasSpaceStation2": 1
          }
        },
        {
          "coordinate": "SNDST-C-766926738-0-0-0",
          "cluster": "SNDST-C",
          "dlcs": [
            "FrostyPlanet",
            "SpacedOut"
          ],
          "worldTraitsOfStarter": [],
          "geysersCountOfStarter": {
            "COOL_STEAM": 2,
            "COOL_SLUSH_WATER": 1,
            "COOL_SALT_WATER": 1,
            "NATURAL_GAS": 1,
            "MINOR_VOLCANO": 3,
            "HYDROGEN": 1,
            "CHLORINE": 1
          },
          "starMapEntryCounts": {
            "TerraMoonlet": 1,
            "IdealLandingSite": 1,
            "WarpOilySwamp": 1,
            "TundraMoonlet": 1,
            "MarshyMoonlet": 1,
            "MooMoonlet": 1,
            "WaterMoonlet": 1,
            "NiobiumMoonlet": 1,
            "RegolithMoonlet": 1,
            "TemporalTear": 1,
            "HarvestableSpacePOI_SandyOreField": 1,
            "HarvestableSpacePOI_OrganicMassField": 1,
            "HarvestableSpacePOI_GlimmeringAsteroidField": 2,
            "HarvestableSpacePOI_OilyAsteroidField": 2,
            "HarvestableSpacePOI_GildedAsteroidField": 2,
            "HarvestableSpacePOI_FrozenOreField": 1,
            "HarvestableSpacePOI_HeliumCloud": 2,
            "HarvestableSpacePOI_RadioactiveGasCloud": 2,
            "HarvestableSpacePOI_RadioactiveAsteroidField": 1,
            "HarvestableSpacePOI_InterstellarIceField": 1,
            "HarvestableSpacePOI_InterstellarOcean": 1,
            "HarvestableSpacePOI_RockyAsteroidField": 2,
            "HarvestableSpacePOI_ForestyOreField": 1,
            "HarvestableSpacePOI_SatelliteField": 2,
            "HarvestableSpacePOI_OxidizedAsteroidField": 1,
            "HarvestableSpacePOI_OxygenRichAsteroidField": 1,
            "HarvestableSpacePOI_MetallicAsteroidField": 1,
            "ArtifactSpacePOI_GravitasSpaceStation6": 1,
            "ArtifactSpacePOI_RussellsTeapot": 1,
            "ArtifactSpacePOI_GravitasSpaceStation5": 1
          }
        },
        {
          "coordinate": "SNDST-C-401639188-0-0-0",
          "cluster": "SNDST-C",
          "dlcs": [
            "FrostyPlanet",
            "SpacedOut"
          ],
          "worldTraitsOfStarter": [],
          "geysersCountOfStarter": {
            "COOL_STEAM": 2,
            "COOL_SLUSH_WATER": 1,
            "COOL_SALT_WATER": 1,
            "NATURAL_GAS": 1,
            "MINOR_VOLCANO": 3,
            "HYDROGEN": 1,
            "VOLCANO": 1
          },
          "starMapEntryCounts": {
            "TerraMoonlet": 1,
            "IdealLandingSite": 1,
            "WarpOilySwamp": 1,
            "TundraMoonlet": 1,
            "MarshyMoonlet": 1,
            "MooMoonlet": 1,
            "WaterMoonlet": 1,
            "NiobiumMoonlet": 1,
            "RegolithMoonlet": 1,
            "TemporalTear": 1,
            "HarvestableSpacePOI_SandyOreField": 1,
            "HarvestableSpacePOI_OrganicMassField": 3,
            "HarvestableSpacePOI_FrozenOreField": 1,
            "HarvestableSpacePOI_GlimmeringAsteroidField": 2,
            "HarvestableSpacePOI_OilyAsteroidField": 2,
            "HarvestableSpacePOI_GildedAsteroidField": 1,
            "HarvestableSpacePOI_HeliumCloud": 2,
            "HarvestableSpacePOI_RadioactiveAsteroidField": 1,
            "HarvestableSpacePOI_RadioactiveGasCloud": 3,
            "HarvestableSpacePOI_InterstellarIceField": 1,
            "HarvestableSpacePOI_SwampyOreField": 1,
            "HarvestableSpacePOI_RockyAsteroidField": 1,
            "HarvestableSpacePOI_CarbonAsteroidField": 1,
            "HarvestableSpacePOI_OxygenRichAsteroidField": 1,
            "HarvestableSpacePOI_IceAsteroidField": 1,
            "HarvestableSpacePOI_SatelliteField": 1,
            "HarvestableSpacePOI_SaltyAsteroidField": 1,
            "ArtifactSpacePOI_GravitasSpaceStation1": 1,
            "ArtifactSpacePOI_RussellsTeapot": 1,
            "ArtifactSpacePOI_GravitasSpaceStation3": 1,
            "ArtifactSpacePOI_GravitasSpaceStation2": 1
          }
        },
        {
          "coordinate": "SNDST-C-1570393224-0-0-0",
          "cluster": "SNDST-C",
          "dlcs": [
            "FrostyPlanet",
            "SpacedOut"
          ],
          "worldTraitsOfStarter": [],
          "geysersCountOfStarter": {
            "COOL_STEAM": 1,
            "COOL_SALT_WATER": 1,
            "COOL_SLUSH_WATER": 1,
            "NATURAL_GAS": 1,
            "MINOR_VOLCANO": 3,
            "HYDROGEN": 1,
            "VOLCANO": 1,
            "CHLORINE": 1
          },
          "starMapEntryCounts": {
            "TerraMoonlet": 2,
            "IdealLandingSite": 2,
            "WarpOilySwamp": 2,
            "TundraMoonlet": 2,
            "MarshyMoonlet": 2,
            "MooMoonlet": 2,
            "WaterMoonlet": 2,
            "NiobiumMoonlet": 2,
            "RegolithMoonlet": 2,
            "TemporalTear": 2,
            "HarvestableSpacePOI_SandyOreField": 2,
            "HarvestableSpacePOI_OrganicMassField": 4,
            "HarvestableSpacePOI_FrozenOreField": 3,
            "HarvestableSpacePOI_GlimmeringAsteroidField": 3,
            "HarvestableSpacePOI_OilyAsteroidField": 3,
            "HarvestableSpacePOI_GildedAsteroidField": 3,
            "HarvestableSpacePOI_HeliumCloud": 4,
            "HarvestableSpacePOI_RadioactiveAsteroidField": 2,
            "HarvestableSpacePOI_RadioactiveGasCloud": 5,
            "HarvestableSpacePOI_InterstellarIceField": 1,
            "HarvestableSpacePOI_SwampyOreField": 2,
            "HarvestableSpacePOI_RockyAsteroidField": 1,
            "HarvestableSpacePOI_CarbonAsteroidField": 3,
            "HarvestableSpacePOI_OxygenRichAsteroidField": 1,
            "HarvestableSpacePOI_IceAsteroidField": 2,
            "HarvestableSpacePOI_SatelliteField": 1,
            "HarvestableSpacePOI_SaltyAsteroidField": 1,
            "ArtifactSpacePOI_GravitasSpaceStation1": 1,
            "ArtifactSpacePOI_RussellsTeapot": 2,
            "ArtifactSpacePOI_GravitasSpaceStation3": 1,
            "ArtifactSpacePOI_GravitasSpaceStation2": 2,
            "HarvestableSpacePOI_ForestyOreField": 4,
            "HarvestableSpacePOI_ChlorineCloud": 1,
            "HarvestableSpacePOI_OxidizedAsteroidField": 2,
            "ArtifactSpacePOI_GravitasSpaceStation8": 1
          }
        },
        {
          "coordinate": "SNDST-C-1821767789-0-0-0",
          "cluster": "SNDST-C",
          "dlcs": [
            "FrostyPlanet",
            "SpacedOut"
          ],
          "worldTraitsOfStarter": [],
          "geysersCountOfStarter": {
            "COOL_STEAM": 1,
            "COOL_SLUSH_WATER": 1,
            "COOL_SALT_WATER": 1,
            "NATURAL_GAS": 1,
            "MINOR_VOLCANO": 3,
            "VOLCANO": 1,
            "HYDROGEN": 1,
            "CHLORINE": 1
          },
          "starMapEntryCounts": {
            "TerraMoonlet": 1,
            "IdealLandingSite": 1,
            "WarpOilySwamp": 1,
            "TundraMoonlet": 1,
            "MarshyMoonlet": 1,
            "MooMoonlet": 1,
            "WaterMoonlet": 1,
            "NiobiumMoonlet": 1,
            "RegolithMoonlet": 1,
            "TemporalTear": 1,
            "HarvestableSpacePOI_SandyOreField": 1,
            "HarvestableSpacePOI_OrganicMassField": 1,
            "HarvestableSpacePOI_HeliumCloud": 1,
            "HarvestableSpacePOI_GildedAsteroidField": 1,
            "HarvestableSpacePOI_GlimmeringAsteroidField": 2,
            "HarvestableSpacePOI_FrozenOreField": 1,
            "HarvestableSpacePOI_OilyAsteroidField": 1,
            "HarvestableSpacePOI_RadioactiveGasCloud": 4,
            "HarvestableSpacePOI_RadioactiveAsteroidField": 2,
            "HarvestableSpacePOI_RockyAsteroidField": 3,
            "HarvestableSpacePOI_InterstellarIceField": 1,
            "HarvestableSpacePOI_ForestyOreField": 1,
            "HarvestableSpacePOI_SatelliteField": 1,
            "HarvestableSpacePOI_OxidizedAsteroidField": 1,
            "HarvestableSpacePOI_SaltyAsteroidField": 2,
            "HarvestableSpacePOI_ChlorineCloud": 1,
            "ArtifactSpacePOI_GravitasSpaceStation6": 1,
            "ArtifactSpacePOI_RussellsTeapot": 1,
            "ArtifactSpacePOI_GravitasSpaceStation5": 1,
            "ArtifactSpacePOI_GravitasSpaceStation2": 1
          }
        },
        {
          "coordinate": "SNDST-C-2073281324-0-0-0",
          "cluster": "SNDST-C",
          "dlcs": [
            "FrostyPlanet",
            "SpacedOut"
          ],
          "worldTraitsOfStarter": [],
          "geysersCountOfStarter": {
            "COOL_STEAM": 1,
            "COOL_SALT_WATER": 1,
            "COOL_SLUSH_WATER": 1,
            "NATURAL_GAS": 2,
            "MINOR_VOLCANO": 2,
            "CHLORINE": 1,
            "HOT_POLLUTED_O2": 1
          },
          "starMapEntryCounts": {
            "TerraMoonlet": 1,
            "IdealLandingSite": 1,
            "WarpOilySwamp": 1,
            "TundraMoonlet": 1,
            "MarshyMoonlet": 1,
            "MooMoonlet": 1,
            "WaterMoonlet": 1,
            "NiobiumMoonlet": 1,
            "RegolithMoonlet": 1,
            "TemporalTear": 1,
            "HarvestableSpacePOI_SandyOreField": 1,
            "HarvestableSpacePOI_OrganicMassField": 1,
            "HarvestableSpacePOI_GlimmeringAsteroidField": 1,
            "HarvestableSpacePOI_HeliumCloud": 3,
            "HarvestableSpacePOI_OilyAsteroidField": 1,
            "HarvestableSpacePOI_FrozenOreField": 1,
            "HarvestableSpacePOI_GildedAsteroidField": 2,
            "HarvestableSpacePOI_RadioactiveGasCloud": 1,
            "HarvestableSpacePOI_RadioactiveAsteroidField": 1,
            "HarvestableSpacePOI_ForestyOreField": 3,
            "HarvestableSpacePOI_SwampyOreField": 1,
            "HarvestableSpacePOI_InterstellarOcean": 1,
            "HarvestableSpacePOI_SatelliteField": 1,
            "HarvestableSpacePOI_SaltyAsteroidField": 1,
            "HarvestableSpacePOI_ChlorineCloud": 1,
            "HarvestableSpacePOI_GasGiantCloud": 1,
            "HarvestableSpacePOI_OxidizedAsteroidField": 1,
            "HarvestableSpacePOI_MetallicAsteroidField": 1,
            "HarvestableSpacePOI_CarbonAsteroidField": 1,
            "ArtifactSpacePOI_GravitasSpaceStation4": 1,
            "ArtifactSpacePOI_RussellsTeapot": 1,
            "ArtifactSpacePOI_GravitasSpaceStation7": 1
          }
        },
        {
          "coordinate": "SNDST-C-1397180885-0-0-0",
          "cluster": "SNDST-C",
          "dlcs": [
            "FrostyPlanet",
            "SpacedOut"
          ],
          "worldTraitsOfStarter": [],
          "geysersCountOfStarter": {
            "COOL_STEAM": 2,
            "COOL_SALT_WATER": 1,
            "COOL_SLUSH_WATER": 1,
            "NATURAL_GAS": 1,
            "MINOR_VOLCANO": 3,
            "LIQUID_CO2": 2
          },
          "starMapEntryCounts": {
            "TerraMoonlet": 1,
            "IdealLandingSite": 1,
            "WarpOilySwamp": 1,
            "TundraMoonlet": 1,
            "MarshyMoonlet": 1,
            "MooMoonlet": 1,
            "WaterMoonlet": 1,
            "NiobiumMoonlet": 1,
            "RegolithMoonlet": 1,
            "TemporalTear": 1,
            "HarvestableSpacePOI_SandyOreField": 1,
            "HarvestableSpacePOI_OrganicMassField": 1,
            "HarvestableSpacePOI_GildedAsteroidField": 2,
            "HarvestableSpacePOI_FrozenOreField": 2,
            "HarvestableSpacePOI_OilyAsteroidField": 1,
            "HarvestableSpacePOI_HeliumCloud": 2,
            "HarvestableSpacePOI_GlimmeringAsteroidField": 2,
            "HarvestableSpacePOI_RadioactiveGasCloud": 1,
            "HarvestableSpacePOI_RadioactiveAsteroidField": 2,
            "HarvestableSpacePOI_RockyAsteroidField": 1,
            "HarvestableSpacePOI_SwampyOreField": 3,
            "HarvestableSpacePOI_InterstellarIceField": 1,
            "HarvestableSpacePOI_ChlorineCloud": 1,
            "HarvestableSpacePOI_CarbonAsteroidField": 2,
            "HarvestableSpacePOI_OxygenRichAsteroidField": 1,
            "HarvestableSpacePOI_OxidizedAsteroidField": 1,
            "ArtifactSpacePOI_GravitasSpaceStation6": 1,
            "ArtifactSpacePOI_RussellsTeapot": 1,
            "ArtifactSpacePOI_GravitasSpaceStation8": 1,
            "ArtifactSpacePOI_GravitasSpaceStation2": 1,
            "ArtifactSpacePOI_GravitasSpaceStation7": 1,
            "ArtifactSpacePOI_GravitasSpaceStation5": 1
          }
        },
        {
          "coordinate": "SNDST-C-1829743387-0-0-0",
          "cluster": "SNDST-C",
          "dlcs": [
            "FrostyPlanet",
            "SpacedOut"
          ],
          "worldTraitsOfStarter": [],
          "geysersCountOfStarter": {
            "COOL_STEAM": 3,
            "COOL_SALT_WATER": 1,
            "COOL_SLUSH_WATER": 1,
            "NATURAL_GAS": 1,
            "MINOR_VOLCANO": 2,
            "VOLCANO": 1
          },
          "starMapEntryCounts": {
            "TerraMoonlet": 1,
            "IdealLandingSite": 1,
            "WarpOilySwamp": 1,
            "TundraMoonlet": 1,
            "MarshyMoonlet": 1,
            "MooMoonlet": 1,
            "WaterMoonlet": 1,
            "NiobiumMoonlet": 1,
            "RegolithMoonlet": 1,
            "TemporalTear": 1,
            "HarvestableSpacePOI_SandyOreField": 1,
            "HarvestableSpacePOI_OrganicMassField": 2,
            "HarvestableSpacePOI_HeliumCloud": 1,
            "HarvestableSpacePOI_OilyAsteroidField": 2,
            "HarvestableSpacePOI_FrozenOreField": 2,
            "HarvestableSpacePOI_GildedAsteroidField": 1,
            "HarvestableSpacePOI_GlimmeringAsteroidField": 1,
            "HarvestableSpacePOI_RadioactiveGasCloud": 2,
            "HarvestableSpacePOI_RadioactiveAsteroidField": 2,
            "HarvestableSpacePOI_InterstellarIceField": 3,
            "HarvestableSpacePOI_InterstellarOcean": 1,
            "HarvestableSpacePOI_ChlorineCloud": 1,
            "HarvestableSpacePOI_SaltyAsteroidField": 4,
            "HarvestableSpacePOI_SatelliteField": 1,
            "ArtifactSpacePOI_GravitasSpaceStation6": 1,
            "ArtifactSpacePOI_RussellsTeapot": 1,
            "ArtifactSpacePOI_GravitasSpaceStation3": 1,
            "ArtifactSpacePOI_GravitasSpaceStation5": 1,
            "ArtifactSpacePOI_GravitasSpaceStation2": 1
          }
        },
        {
          "coordinate": "SNDST-C-370816749-0-0-0",
          "cluster": "SNDST-C",
          "dlcs": [
            "FrostyPlanet",
            "SpacedOut"
          ],
          "worldTraitsOfStarter": [],
          "geysersCountOfStarter": {
            "COOL_STEAM": 1,
            "COOL_SALT_WATER": 1,
            "COOL_SLUSH_WATER": 1,
            "NATURAL_GAS": 2,
            "MINOR_VOLCANO": 3,
            "LIQUID_CO2": 2
          },
          "starMapEntryCounts": {
            "TerraMoonlet": 1,
            "IdealLandingSite": 1,
            "WarpOilySwamp": 1,
            "TundraMoonlet": 1,
            "MarshyMoonlet": 1,
            "MooMoonlet": 1,
            "WaterMoonlet": 1,
            "NiobiumMoonlet": 1,
            "RegolithMoonlet": 1,
            "TemporalTear": 1,
            "HarvestableSpacePOI_SandyOreField": 1,
            "HarvestableSpacePOI_OrganicMassField": 2,
            "HarvestableSpacePOI_FrozenOreField": 1,
            "HarvestableSpacePOI_GlimmeringAsteroidField": 2,
            "HarvestableSpacePOI_OilyAsteroidField": 1,
            "HarvestableSpacePOI_GildedAsteroidField": 1,
            "HarvestableSpacePOI_HeliumCloud": 2,
            "HarvestableSpacePOI_RadioactiveGasCloud": 1,
            "HarvestableSpacePOI_RadioactiveAsteroidField": 4,
            "HarvestableSpacePOI_RockyAsteroidField": 1,
            "HarvestableSpacePOI_ForestyOreField": 1,
            "HarvestableSpacePOI_InterstellarOcean": 1,
            "HarvestableSpacePOI_SwampyOreField": 1,
            "HarvestableSpacePOI_IceAsteroidField": 1,
            "HarvestableSpacePOI_OxidizedAsteroidField": 1,
            "HarvestableSpacePOI_SatelliteField": 1,
            "HarvestableSpacePOI_ChlorineCloud": 1,
            "HarvestableSpacePOI_CarbonAsteroidField": 1,
            "ArtifactSpacePOI_GravitasSpaceStation1": 1,
            "ArtifactSpacePOI_RussellsTeapot": 1,
            "ArtifactSpacePOI_GravitasSpaceStation2": 1,
            "ArtifactSpacePOI_GravitasSpaceStation5": 1,
            "ArtifactSpacePOI_GravitasSpaceStation8": 1
          }
        },
        {
          "coordinate": "SNDST-C-278861024-0-0-0",
          "cluster": "SNDST-C",
          "dlcs": [
            "FrostyPlanet",
            "SpacedOut"
          ],
          "worldTraitsOfStarter": [],
          "geysersCountOfStarter": {
            "COOL_STEAM": 2,
            "COOL_SALT_WATER": 1,
            "COOL_SLUSH_WATER": 1,
            "NATURAL_GAS": 2,
            "MINOR_VOLCANO": 3,
            "POLLUTED_WATER": 1
          },
          "starMapEntryCounts": {
            "TerraMoonlet": 1,
            "IdealLandingSite": 1,
            "WarpOilySwamp": 1,
            "TundraMoonlet": 1,
            "MarshyMoonlet": 1,
            "MooMoonlet": 1,
            "WaterMoonlet": 1,
            "NiobiumMoonlet": 1,
            "RegolithMoonlet": 1,
            "TemporalTear": 1,
            "HarvestableSpacePOI_SandyOreField": 1,
            "HarvestableSpacePOI_OrganicMassField": 2,
            "HarvestableSpacePOI_GildedAsteroidField": 1,
            "HarvestableSpacePOI_OilyAsteroidField": 1,
            "HarvestableSpacePOI_GlimmeringAsteroidField": 1,
            "HarvestableSpacePOI_HeliumCloud": 2,
            "HarvestableSpacePOI_FrozenOreField": 2,
            "HarvestableSpacePOI_RadioactiveGasCloud": 1,
            "HarvestableSpacePOI_RadioactiveAsteroidField": 1,
            "HarvestableSpacePOI_ForestyOreField": 3,
            "HarvestableSpacePOI_SwampyOreField": 1,
            "HarvestableSpacePOI_SaltyAsteroidField": 1,
            "HarvestableSpacePOI_GasGiantCloud": 2,
            "HarvestableSpacePOI_SatelliteField": 1,
            "HarvestableSpacePOI_OxidizedAsteroidField": 2,
            "HarvestableSpacePOI_CarbonAsteroidField": 1,
            "HarvestableSpacePOI_MetallicAsteroidField": 1,
            "ArtifactSpacePOI_RussellsTeapot": 1,
            "ArtifactSpacePOI_GravitasSpaceStation7": 1,
            "ArtifactSpacePOI_GravitasSpaceStation5": 1
          }
        },
        {
          "coordinate": "SNDST-C-55471948-0-0-0",
          "cluster": "SNDST-C",
          "dlcs": [
            "FrostyPlanet",
            "SpacedOut"
          ],
          "worldTraitsOfStarter": [],
          "geysersCountOfStarter": {
            "COOL_STEAM": 2,
            "COOL_SLUSH_WATER": 1,
            "COOL_SALT_WATER": 1,
            "NATURAL_GAS": 1,
            "MINOR_VOLCANO": 3,
            "CHLORINE": 1,
            "POLLUTED_WATER": 1
          },
          "starMapEntryCounts": {
            "TerraMoonlet": 1,
            "IdealLandingSite": 1,
            "WarpOilySwamp": 1,
            "TundraMoonlet": 1,
            "MarshyMoonlet": 1,
            "MooMoonlet": 1,
            "WaterMoonlet": 1,
            "NiobiumMoonlet": 1,
            "RegolithMoonlet": 1,
            "TemporalTear": 1,
            "HarvestableSpacePOI_SandyOreField": 1,
            "HarvestableSpacePOI_OrganicMassField": 1,
            "HarvestableSpacePOI_HeliumCloud": 1,
            "HarvestableSpacePOI_GlimmeringAsteroidField": 2,
            "HarvestableSpacePOI_GildedAsteroidField": 2,
            "HarvestableSpacePOI_OilyAsteroidField": 2,
            "HarvestableSpacePOI_FrozenOreField": 2,
            "HarvestableSpacePOI_RadioactiveAsteroidField": 3,
            "HarvestableSpacePOI_RadioactiveGasCloud": 1,
            "HarvestableSpacePOI_InterstellarIceField": 2,
            "HarvestableSpacePOI_ForestyOreField": 1,
            "HarvestableSpacePOI_RockyAsteroidField": 2,
            "HarvestableSpacePOI_CarbonAsteroidField": 1,
            "HarvestableSpacePOI_ChlorineCloud": 1,
            "HarvestableSpacePOI_GasGiantCloud": 1,
            "HarvestableSpacePOI_OxygenRichAsteroidField": 1,
            "ArtifactSpacePOI_RussellsTeapot": 1,
            "ArtifactSpacePOI_GravitasSpaceStation8": 1
          }
        },
        {
          "coordinate": "SNDST-C-693823529-0-0-0",
          "cluster": "SNDST-C",
          "dlcs": [
            "FrostyPlanet",
            "SpacedOut"
          ],
          "worldTraitsOfStarter": [],
          "geysersCountOfStarter": {
            "COOL_STEAM": 1,
            "COOL_SALT_WATER": 1,
            "COOL_SLUSH_WATER": 1,
            "NATURAL_GAS": 1,
            "MINOR_VOLCANO": 3,
            "POLLUTED_WATER": 1,
            "HOT_POLLUTED_O2": 1,
            "LIQUID_CO2": 1
          },
          "starMapEntryCounts": {
            "TerraMoonlet": 1,
            "IdealLandingSite": 1,
            "WarpOilySwamp": 1,
            "TundraMoonlet": 1,
            "MarshyMoonlet": 1,
            "MooMoonlet": 1,
            "WaterMoonlet": 1,
            "NiobiumMoonlet": 1,
            "RegolithMoonlet": 1,
            "TemporalTear": 1,
            "HarvestableSpacePOI_SandyOreField": 1,
            "HarvestableSpacePOI_OrganicMassField": 2,
            "HarvestableSpacePOI_HeliumCloud": 1,
            "HarvestableSpacePOI_FrozenOreField": 4,
            "HarvestableSpacePOI_GildedAsteroidField": 2,
            "HarvestableSpacePOI_GlimmeringAsteroidField": 1,
            "HarvestableSpacePOI_OilyAsteroidField": 2,
            "HarvestableSpacePOI_RadioactiveGasCloud": 1,
            "HarvestableSpacePOI_RadioactiveAsteroidField": 1,
            "HarvestableSpacePOI_RockyAsteroidField": 1,
            "HarvestableSpacePOI_InterstellarOcean": 1,
            "HarvestableSpacePOI_ForestyOreField": 2,
            "HarvestableSpacePOI_CarbonAsteroidField": 1,
            "HarvestableSpacePOI_MetallicAsteroidField": 2,
            "HarvestableSpacePOI_OxidizedAsteroidField": 1,
            "HarvestableSpacePOI_OxygenRichAsteroidField": 1,
            "ArtifactSpacePOI_GravitasSpaceStation4": 1,
            "ArtifactSpacePOI_RussellsTeapot": 1,
            "ArtifactSpacePOI_GravitasSpaceStation2": 1,
            "ArtifactSpacePOI_GravitasSpaceStation7": 1
          }
        },
        {
          "coordinate": "SNDST-C-1126135245-0-0-0",
          "cluster": "SNDST-C",
          "dlcs": [
            "FrostyPlanet",
            "SpacedOut"
          ],
          "worldTraitsOfStarter": [],
          "geysersCountOfStarter": {
            "COOL_STEAM": 1,
            "COOL_SALT_WATER": 1,
            "COOL_SLUSH_WATER": 1,
            "NATURAL_GAS": 1,
            "MINOR_VOLCANO": 3,
            "CHLORINE": 2,
            "HOT_POLLUTED_O2": 1
          },
          "starMapEntryCounts": {
            "TerraMoonlet": 1,
            "IdealLandingSite": 1,
            "WarpOilySwamp": 1,
            "TundraMoonlet": 1,
            "MarshyMoonlet": 1,
            "MooMoonlet": 1,
            "WaterMoonlet": 1,
            "NiobiumMoonlet": 1,
            "RegolithMoonlet": 1,
            "TemporalTear": 1,
            "HarvestableSpacePOI_SandyOreField": 1,
            "HarvestableSpacePOI_OrganicMassField": 2,
            "HarvestableSpacePOI_FrozenOreField": 2,
            "HarvestableSpacePOI_GlimmeringAsteroidField": 1,
            "HarvestableSpacePOI_GildedAsteroidField": 2,
            "HarvestableSpacePOI_HeliumCloud": 1,
            "HarvestableSpacePOI_OilyAsteroidField": 3,
            "HarvestableSpacePOI_RadioactiveAsteroidField": 1,
            "HarvestableSpacePOI_RadioactiveGasCloud": 2,
            "HarvestableSpacePOI_RockyAsteroidField": 1,
            "HarvestableSpacePOI_SwampyOreField": 2,
            "HarvestableSpacePOI_InterstellarOcean": 1,
            "HarvestableSpacePOI_GasGiantCloud": 1,
            "HarvestableSpacePOI_SatelliteField": 3,
            "HarvestableSpacePOI_SaltyAsteroidField": 1,
            "ArtifactSpacePOI_RussellsTeapot": 1,
            "ArtifactSpacePOI_GravitasSpaceStation8": 1
          }
        },
        {
          "coordinate": "SNDST-C-1489697521-0-0-0",
          "cluster": "SNDST-C",
          "dlcs": [
            "FrostyPlanet",
            "SpacedOut"
          ],
          "worldTraitsOfStarter": [],
          "geysersCountOfStarter": {
            "COOL_STEAM": 1,
            "COOL_SLUSH_WATER": 1,
            "COOL_SALT_WATER": 1,
            "NATURAL_GAS": 1,
            "MINOR_VOLCANO": 3,
            "LIQUID_CO2": 2,
            "HYDROGEN": 1
          },
          "starMapEntryCounts": {
            "TerraMoonlet": 1,
            "IdealLandingSite": 1,
            "WarpOilySwamp": 1,
            "TundraMoonlet": 1,
            "MarshyMoonlet": 1,
            "MooMoonlet": 1,
            "WaterMoonlet": 1,
            "NiobiumMoonlet": 1,
            "RegolithMoonlet": 1,
            "TemporalTear": 1,
            "HarvestableSpacePOI_SandyOreField": 1,
            "HarvestableSpacePOI_OrganicMassField": 3,
            "HarvestableSpacePOI_GlimmeringAsteroidField": 2,
            "HarvestableSpacePOI_HeliumCloud": 2,
            "HarvestableSpacePOI_GildedAsteroidField": 1,
            "HarvestableSpacePOI_FrozenOreField": 3,
            "HarvestableSpacePOI_OilyAsteroidField": 1,
            "HarvestableSpacePOI_RadioactiveAsteroidField": 4,
            "HarvestableSpacePOI_RadioactiveGasCloud": 1,
            "HarvestableSpacePOI_SwampyOreField": 1,
            "HarvestableSpacePOI_InterstellarIceField": 1,
            "HarvestableSpacePOI_CarbonAsteroidField": 1,
            "HarvestableSpacePOI_OxidizedAsteroidField": 1,
            "HarvestableSpacePOI_ChlorineCloud": 1,
            "ArtifactSpacePOI_GravitasSpaceStation6": 1,
            "ArtifactSpacePOI_RussellsTeapot": 1,
            "ArtifactSpacePOI_GravitasSpaceStation5": 1,
            "ArtifactSpacePOI_GravitasSpaceStation8": 1,
            "ArtifactSpacePOI_GravitasSpaceStation2": 1
          }
        },
        {
          "coordinate": "SNDST-C-704946202-0-0-0",
          "cluster": "SNDST-C",
          "dlcs": [
            "FrostyPlanet",
            "SpacedOut"
          ],
          "worldTraitsOfStarter": [],
          "geysersCountOfStarter": {
            "COOL_STEAM": 1,
            "COOL_SALT_WATER": 1,
            "COOL_SLUSH_WATER": 1,
            "NATURAL_GAS": 1,
            "MINOR_VOLCANO": 3,
            "HOT_POLLUTED_O2": 1,
            "POLLUTED_WATER": 1,
            "CHLORINE": 1
          },
          "starMapEntryCounts": {
            "TerraMoonlet": 1,
            "IdealLandingSite": 1,
            "WarpOilySwamp": 1,
            "TundraMoonlet": 1,
            "MarshyMoonlet": 1,
            "MooMoonlet": 1,
            "WaterMoonlet": 1,
            "NiobiumMoonlet": 1,
            "RegolithMoonlet": 1,
            "TemporalTear": 1,
            "HarvestableSpacePOI_SandyOreField": 1,
            "HarvestableSpacePOI_OrganicMassField": 3,
            "HarvestableSpacePOI_GildedAsteroidField": 2,
            "HarvestableSpacePOI_FrozenOreField": 1,
            "HarvestableSpacePOI_OilyAsteroidField": 3,
            "HarvestableSpacePOI_HeliumCloud": 2,
            "HarvestableSpacePOI_GlimmeringAsteroidField": 2,
            "HarvestableSpacePOI_RadioactiveAsteroidField": 1,
            "HarvestableSpacePOI_RadioactiveGasCloud": 2,
            "HarvestableSpacePOI_ForestyOreField": 1,
            "HarvestableSpacePOI_SwampyOreField": 1,
            "HarvestableSpacePOI_InterstellarOcean": 1,
            "HarvestableSpacePOI_SaltyAsteroidField": 1,
            "HarvestableSpacePOI_MetallicAsteroidField": 2,
            "HarvestableSpacePOI_ChlorineCloud": 1,
            "ArtifactSpacePOI_GravitasSpaceStation1": 1,
            "ArtifactSpacePOI_RussellsTeapot": 1,
            "ArtifactSpacePOI_GravitasSpaceStation2": 1,
            "ArtifactSpacePOI_GravitasSpaceStation3": 1,
            "ArtifactSpacePOI_GravitasSpaceStation8": 1,
            "ArtifactSpacePOI_GravitasSpaceStation5": 1
          }
        },
        {
          "coordinate": "SNDST-C-1586710390-0-0-0",
          "cluster": "SNDST-C",
          "dlcs": [
            "FrostyPlanet",
            "SpacedOut"
          ],
          "worldTraitsOfStarter": [],
          "geysersCountOfStarter": {
            "COOL_STEAM": 2,
            "COOL_SALT_WATER": 1,
            "COOL_SLUSH_WATER": 1,
            "NATURAL_GAS": 1,
            "MINOR_VOLCANO": 3,
            "POLLUTED_WATER": 1,
            "HYDROGEN": 1
          },
          "starMapEntryCounts": {
            "TerraMoonlet": 1,
            "IdealLandingSite": 1,
            "WarpOilySwamp": 1,
            "TundraMoonlet": 1,
            "MarshyMoonlet": 1,
            "MooMoonlet": 1,
            "WaterMoonlet": 1,
            "NiobiumMoonlet": 1,
            "RegolithMoonlet": 1,
            "TemporalTear": 1,
            "HarvestableSpacePOI_SandyOreField": 1,
            "HarvestableSpacePOI_OrganicMassField": 1,
            "HarvestableSpacePOI_GlimmeringAsteroidField": 1,
            "HarvestableSpacePOI_HeliumCloud": 3,
            "HarvestableSpacePOI_FrozenOreField": 1,
            "HarvestableSpacePOI_GildedAsteroidField": 3,
            "HarvestableSpacePOI_OilyAsteroidField": 1,
            "HarvestableSpacePOI_RadioactiveGasCloud": 2,
            "HarvestableSpacePOI_RadioactiveAsteroidField": 1,
            "HarvestableSpacePOI_InterstellarOcean": 1,
            "HarvestableSpacePOI_ForestyOreField": 4,
            "HarvestableSpacePOI_MetallicAsteroidField": 1,
            "HarvestableSpacePOI_OxygenRichAsteroidField": 1,
            "HarvestableSpacePOI_CarbonAsteroidField": 1,
            "HarvestableSpacePOI_OxidizedAsteroidField": 1,
            "HarvestableSpacePOI_ChlorineCloud": 1,
            "ArtifactSpacePOI_GravitasSpaceStation4": 1,
            "ArtifactSpacePOI_RussellsTeapot": 1,
            "ArtifactSpacePOI_GravitasSpaceStation8": 1,
            "ArtifactSpacePOI_GravitasSpaceStation5": 1,
            "ArtifactSpacePOI_GravitasSpaceStation3": 1
          }
        },
        {
          "coordinate": "SNDST-C-1331944616-0-0-0",
          "cluster": "SNDST-C",
          "dlcs": [
            "FrostyPlanet",
            "SpacedOut"
          ],
          "worldTraitsOfStarter": [],
          "geysersCountOfStarter": {
            "COOL_STEAM": 1,
            "COOL_SLUSH_WATER": 1,
            "COOL_SALT_WATER": 1,
            "NATURAL_GAS": 1,
            "MINOR_VOLCANO": 3,
            "HYDROGEN": 1,
            "LIQUID_CO2": 1,
            "POLLUTED_WATER": 1
          },
          "starMapEntryCounts": {
            "TerraMoonlet": 1,
            "IdealLandingSite": 1,
            "WarpOilySwamp": 1,
            "TundraMoonlet": 1,
            "MarshyMoonlet": 1,
            "MooMoonlet": 1,
            "WaterMoonlet": 1,
            "NiobiumMoonlet": 1,
            "RegolithMoonlet": 1,
            "TemporalTear": 1,
            "HarvestableSpacePOI_SandyOreField": 1,
            "HarvestableSpacePOI_OrganicMassField": 1,
            "HarvestableSpacePOI_FrozenOreField": 2,
            "HarvestableSpacePOI_GildedAsteroidField": 1,
            "HarvestableSpacePOI_HeliumCloud": 1,
            "HarvestableSpacePOI_OilyAsteroidField": 2,
            "HarvestableSpacePOI_GlimmeringAsteroidField": 1,
            "HarvestableSpacePOI_RadioactiveAsteroidField": 2,
            "HarvestableSpacePOI_RadioactiveGasCloud": 1,
            "HarvestableSpacePOI_InterstellarOcean": 1,
            "HarvestableSpacePOI_ForestyOreField": 1,
            "HarvestableSpacePOI_SwampyOreField": 1,
            "HarvestableSpacePOI_InterstellarIceField": 1,
            "HarvestableSpacePOI_RockyAsteroidField": 1,
            "HarvestableSpacePOI_SatelliteField": 1,
            "HarvestableSpacePOI_MetallicAsteroidField": 1,
            "HarvestableSpacePOI_GasGiantCloud": 1,
            "HarvestableSpacePOI_SaltyAsteroidField": 2,
            "HarvestableSpacePOI_ChlorineCloud": 1,
            "HarvestableSpacePOI_CarbonAsteroidField": 1,
            "ArtifactSpacePOI_GravitasSpaceStation1": 1,
            "ArtifactSpacePOI_RussellsTeapot": 1
          }
        },
        {
          "coordinate": "SNDST-C-896589116-0-0-0",
          "cluster": "SNDST-C",
          "dlcs": [
            "FrostyPlanet",
            "SpacedOut"
          ],
          "worldTraitsOfStarter": [],
          "geysersCountOfStarter": {
            "COOL_STEAM": 2,
            "COOL_SLUSH_WATER": 1,
            "COOL_SALT_WATER": 1,
            "NATURAL_GAS": 1,
            "MINOR_VOLCANO": 3,
            "POLLUTED_WATER": 1,
            "CHLORINE": 1
          },
          "starMapEntryCounts": {
            "TerraMoonlet": 1,
            "IdealLandingSite": 1,
            "WarpOilySwamp": 1,
            "TundraMoonlet": 1,
            "MarshyMoonlet": 1,
            "MooMoonlet": 1,
            "WaterMoonlet": 1,
            "NiobiumMoonlet": 1,
            "RegolithMoonlet": 1,
            "TemporalTear": 1,
            "HarvestableSpacePOI_SandyOreField": 1,
            "HarvestableSpacePOI_OrganicMassField": 2,
            "HarvestableSpacePOI_GlimmeringAsteroidField": 1,
            "HarvestableSpacePOI_GildedAsteroidField": 1,
            "HarvestableSpacePOI_FrozenOreField": 4,
            "HarvestableSpacePOI_OilyAsteroidField": 1,
            "HarvestableSpacePOI_HeliumCloud": 1,
            "HarvestableSpacePOI_RadioactiveAsteroidField": 2,
            "HarvestableSpacePOI_RadioactiveGasCloud": 1,
            "HarvestableSpacePOI_SwampyOreField": 1,
            "HarvestableSpacePOI_CarbonAsteroidField": 1,
            "HarvestableSpacePOI_OxidizedAsteroidField": 1,
            "HarvestableSpacePOI_IceAsteroidField": 2,
            "HarvestableSpacePOI_ChlorineCloud": 1,
            "HarvestableSpacePOI_SatelliteField": 1,
            "ArtifactSpacePOI_GravitasSpaceStation4": 1
          }
        }
      ]
""".trimIndent()
